#!/bin/sh

# exec urxvtc +sb -fg \#ffffff -bg \#000000 "$@" -fn xft:"ubuntu mono:size=10" -letsp -2 $@
# exec urxvtc +sb -fg \#484848 -bg \#ebebeb "$@" -fn xft:lemon
exec urxvtc +sb -fg \#ffffff -bg \#000000 "$@" -fn xft:lemon
#exec urxvtc +sb -fg \#ffffff -bg \#000000 "$@" -fn xft:"ubuntu mono"
